### ISSUE TITLE
Allow to specify path-style of downloaded files

### ISSUE THREAD

**Issue by bhean** [yashprakash13/amusing#1]
Hi, 

Thanks for share this project, it's really nice!
This is not an issue, is a suggestion/improvement.

I just wondering if it´s possible to define the format of the path for the downloaded files. 
At this moment, the files are stored in `<root_download_path>/songs/<album_name>/<song_name> [<song_id>].m4a` and I would like to define my own "structure". 

For example, something similar to `<root_download_path>/songs/<artist-name>/<album-year> - <album_name>/<song_number>.- <song_name>.m4a`

So maybe adding a new parameter to the `appconfig.yaml` to define this path would be great... 

Thanks,

**Comment by yashprakash13** [comment]
Hello, thanks for the suggestion. It should be possible but it'll require a few modifications.

Currently, the project is written for parsing Library.xml from Apple Music and then sorting/downloading songs under <album_name>/<song_name> structure only. The artist name is kept for each song only in the db table. 

However what you're suggesting sounds like it'll need some changes to way I'm parsing the library and then saving the songs. This can be done and I'll add it to my TODOs. 

I'll also welcome a PR if you're so inclined! Currently, I'm focused on adding automatic music metadata tag and coverart fetching features to the downloaded library.

**Comment by yashprakash13** [comment]
This is done.
